name: CI
on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run eslint
        run: pnpm lint

      - name: Run prettier
        run: pnpm format:check

      - name: Run Vitest
        run: pnpm test
